
server:
  port: 8083
  servlet: 
    context-path: /ejob-demo

logging: 
  config: classpath:log4j2-8083.xml

elaticjob: 
  zookeeper: 
    server-lists: 127.0.0.1:2181
    namespace: my-project
    digest: 