
server:
  port: 8080
  servlet: 
    context-path: /ejob-demo

logging: 
  config: classpath:log4j2-8080.xml

elaticjob: 
  zookeeper: 
    server-lists: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    namespace: my-project
    digest: 
    
db: 
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.1.101:3306/world?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
  username: root
  password: root